entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    forwardedHeaders:
      insecure: true
  websecure:
    address: ":8443"
    http:
      tls: {}
    http3:
      advertisedPort: 8443
api:
  dashboard: true
  insecure: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /traefik
    watch: true
experimental:
  plugins:
    log2fuse:
      moduleName: "github.com/peace0phmind/log2fuse"
      version: "v0.10.1"
